name: e_palika
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.9
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/favicon.png"
  adaptive_icon_background: "#336699"
  adaptive_icon_foreground: "assets/images/foreground_favicon.png"

flutter_native_splash:
  color: "#336699"
  image: assets/images/small_favicon.png
  android_12:
    image: "assets/images/small_favicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
